import { MealItem, NGOEntity, InventoryItem, GossipNode } from '../types';

export const SEED_NGOS: NGOEntity[] = [
  {
    id: 'ngo-1',
    name: 'Sewa Foundation Kamla Nagar',
    nameHi: 'सेवा फाउंडेशन कमला नगर',
    type: 'ngo',
    coords: { x: 420, y: 320 },
    capacityDaily: 250,
    openHours: '08:00 AM - 10:30 PM',
    openHoursHi: 'सुबह 8:00 से रात्रि 10:30',
    distanceFromDtuKm: 1.8,
    etaMin: 6,
    contactPerson: 'Anand Prakash',
    phone: '+91 98110 24567',
    address: 'B-14, Chhatra Marg, Kamla Nagar, Delhi 110007',
    addressHi: 'बी-14, छात्र मार्ग, कमला नगर, दिल्ली 110007',
    verified: true
  },
  {
    id: 'ngo-2',
    name: 'Roti Bank Civil Lines',
    nameHi: 'रोटी बैंक सिविल लाइन्स',
    type: 'ngo',
    coords: { x: 560, y: 350 },
    capacityDaily: 350,
    openHours: '07:00 AM - 11:00 PM',
    openHoursHi: 'सुबह 7:00 से रात्रि 11:00',
    distanceFromDtuKm: 3.4,
    etaMin: 12,
    contactPerson: 'Meera Deshmukh',
    phone: '+91 98711 54321',
    address: 'Rajpur Road, Near Metro Station, Civil Lines, Delhi',
    addressHi: 'राजपुर रोड, मेट्रो स्टेशन के पास, सिविल लाइन्स, दिल्ली',
    verified: true
  },
  {
    id: 'ngo-3',
    name: 'Robin Hood Army Delhi (North)',
    nameHi: 'रॉबिन हुड आर्मी दिल्ली (उत्तर)',
    type: 'ngo',
    coords: { x: 480, y: 290 },
    capacityDaily: 400,
    openHours: 'Open 24x7 for Surplus',
    openHoursHi: 'अधिशेष भोजन हेतु 24x7 खुला',
    distanceFromDtuKm: 2.2,
    etaMin: 8,
    contactPerson: 'Vikram Sharma',
    phone: '+91 99580 88219',
    address: 'Mall Road, University Enclave, North Campus, Delhi',
    addressHi: 'मॉल रोड, यूनिवर्सिटी एन्क्लेव, नॉर्थ कैंपस, दिल्ली',
    verified: true
  },
  {
    id: 'ngo-4',
    name: 'Night Shelter Majnu Ka Tila',
    nameHi: 'रैन बसेरा मजनू का टीला',
    type: 'shelter',
    coords: { x: 610, y: 240 },
    capacityDaily: 180,
    openHours: '06:00 PM - 09:00 AM',
    openHoursHi: 'शाम 6:00 से सुबह 9:00',
    distanceFromDtuKm: 4.1,
    etaMin: 14,
    contactPerson: 'Gurpreet Singh',
    phone: '+91 98102 33445',
    address: 'Ring Road, Near Monastery Market, Majnu Ka Tila, Delhi',
    addressHi: 'रिंग रोड, मोनेस्ट्री मार्केट, मजनू का टीला, दिल्ली',
    verified: true
  },
  {
    id: 'ngo-5',
    name: 'Shastri Nagar Community Kitchen',
    nameHi: 'शास्त्री नगर कम्युनिटी किचन',
    type: 'kitchen',
    coords: { x: 340, y: 400 },
    capacityDaily: 220,
    openHours: '09:00 AM - 09:30 PM',
    openHoursHi: 'सुबह 9:00 से रात 9:30',
    distanceFromDtuKm: 3.8,
    etaMin: 11,
    contactPerson: 'Kailash Chand',
    phone: '+91 98681 12908',
    address: 'Block E, Community Hall, Shastri Nagar, Delhi',
    addressHi: 'ब्लॉक ई, कम्युनिटी हॉल, शास्त्री नगर, दिल्ली',
    verified: true
  },
  {
    id: 'ngo-6',
    name: 'Wazirabad Food Bank Center',
    nameHi: 'वजीराबाद फूड बैंक केंद्र',
    type: 'shelter',
    coords: { x: 580, y: 130 },
    capacityDaily: 200,
    openHours: '08:00 AM - 08:00 PM',
    openHoursHi: 'सुबह 8:00 से शाम 8:00',
    distanceFromDtuKm: 4.5,
    etaMin: 15,
    contactPerson: 'Suman Gupta',
    phone: '+91 97177 44002',
    address: 'Main Yamuna Ghat Road, Wazirabad, Delhi',
    addressHi: 'मुख्य यमुना घाट रोड, वजीराबाद, दिल्ली',
    verified: true
  },
  {
    id: 'ngo-7',
    name: 'Vivekanand Puri Seva Kendra',
    nameHi: 'विवेकानंद पुरी सेवा केंद्र',
    type: 'kitchen',
    coords: { x: 320, y: 360 },
    capacityDaily: 160,
    openHours: '10:00 AM - 10:00 PM',
    openHoursHi: 'सुबह 10:00 से रात 10:00',
    distanceFromDtuKm: 3.1,
    etaMin: 10,
    contactPerson: 'Harish Verma',
    phone: '+91 98118 76543',
    address: 'Sector 4, Vivekanand Puri, Sarai Rohilla, Delhi',
    addressHi: 'सेक्टर 4, विवेकानंद पुरी, सराय रोहिल्ला, दिल्ली',
    verified: true
  }
];

export const INITIAL_MEALS: MealItem[] = [
  {
    id: 'meal-001',
    dishName: 'Rajma Chawal + Tawa Roti',
    dishNameHi: 'राजमा चावल + तवा रोटी',
    category: 'meal',
    quantityPlates: 40,
    quantityKg: 14,
    sourceName: 'Atal Canteen (DTU)',
    sourceNameHi: 'अटल कैंटीन (DTU)',
    locationArea: 'DTU Rohini, Delhi',
    locationAreaHi: 'DTU रोहिणी, दिल्ली',
    coords: { x: 200, y: 160 },
    readySinceMinutes: 45,
    safeForHours: 3.8,
    preparedAt: '12:30 PM',
    condition: 'fresh',
    freshnessScore: 94,
    classification: 'DONATE',
    classificationConfidence: 96,
    classificationReason: 'Freshly prepared institutional batch, safely temperature insulated in food-grade thermoware containers.',
    classificationReasonHi: 'ताजा तैयार भोजन, फूड-ग्रेड थर्मल इंसुलेशन बर्तनों में सुरक्षित रूप से संरक्षित।',
    allergens: ['Wheat / Gluten'],
    allergensHi: ['गेहूं / ग्लूटेन'],
    isVeg: true,
    aiVerified: true,
    claimed: false,
    bestMatch: {
      ngoId: 'ngo-1',
      ngoName: 'Sewa Foundation Kamla Nagar',
      ngoNameHi: 'सेवा फाउंडेशन कमला नगर',
      distanceKm: 1.8,
      etaMin: 6,
      lossScore: 0.0875,
      matchScore: 96,
      reasons: ['Nearest verified NGO', 'Direct electric corridor', '250 plate capacity available']
    }
  },
  {
    id: 'meal-002',
    dishName: 'Dal Makhani & Jeera Rice',
    dishNameHi: 'दाल मखनी और जीरा राइस',
    category: 'meal',
    quantityPlates: 65,
    quantityKg: 22,
    sourceName: 'DTU Central Mess (Hostel 7-13)',
    sourceNameHi: 'DTU हॉस्टल मेस (7-13 ब्लॉक)',
    locationArea: 'Hostel Complex, DTU',
    locationAreaHi: 'छात्रावास परिसर, DTU',
    coords: { x: 215, y: 180 },
    readySinceMinutes: 70,
    safeForHours: 3.2,
    preparedAt: '12:00 PM',
    condition: 'fresh',
    freshnessScore: 91,
    classification: 'DONATE',
    classificationConfidence: 94,
    classificationReason: 'Rich protein preparation, maintained at >62°C core steam temperature.',
    classificationReasonHi: 'उच्च प्रोटीन भोजन, 62 डिग्री सेल्सियस से अधिक आंतरिक तापमान पर सुरक्षित।',
    allergens: ['Milk / Lactose'],
    allergensHi: ['दूध / लैक्टोज'],
    isVeg: true,
    aiVerified: true,
    claimed: false,
    bestMatch: {
      ngoId: 'ngo-3',
      ngoName: 'Robin Hood Army Delhi (North)',
      ngoNameHi: 'रॉबिन हुड आर्मी दिल्ली (उत्तर)',
      distanceKm: 2.2,
      etaMin: 8,
      lossScore: 0.0912,
      matchScore: 94,
      reasons: ['Volunteer EV vans active in North Campus', 'Capacity match 400 plates']
    }
  },
  {
    id: 'meal-003',
    dishName: 'Aloo Gobhi + Fresh Phulkas',
    dishNameHi: 'आलू गोभी + ताज़ा फुल्के',
    category: 'meal',
    quantityPlates: 30,
    quantityKg: 10,
    sourceName: 'DTU Faculty Club Canteen',
    sourceNameHi: 'DTU फैकल्टी क्लब कैंटीन',
    locationArea: 'Administrative Block, DTU',
    locationAreaHi: 'प्रशासनिक ब्लॉक, DTU',
    coords: { x: 230, y: 145 },
    readySinceMinutes: 180,
    safeForHours: 1.5,
    preparedAt: '11:15 AM',
    condition: 'stale',
    freshnessScore: 72,
    classification: 'SHELF_LIFE',
    classificationConfidence: 89,
    classificationReason: 'Approaching 3h ambient exposure limit. Safe for consumption; prioritize expedited 60-min distribution.',
    classificationReasonHi: '3 घंटे की सामान्य तापमान सीमा के समीप। खाने योग्य; 60 मिनट के भीतर त्वरित वितरण आवश्यक।',
    allergens: ['Wheat / Gluten'],
    allergensHi: ['गेहूं / ग्लूटेन'],
    isVeg: true,
    aiVerified: true,
    claimed: false,
    bestMatch: {
      ngoId: 'ngo-1',
      ngoName: 'Sewa Foundation Kamla Nagar',
      ngoNameHi: 'सेवा फाउंडेशन कमला नगर',
      distanceKm: 1.8,
      etaMin: 6,
      lossScore: 0.1240,
      matchScore: 91,
      reasons: ['Fastest arrival window 6 minutes']
    }
  },
  {
    id: 'meal-004',
    dishName: 'Vegetable Biryani & Boondi Raita',
    dishNameHi: 'वेज बिरयानी एवं बूंदी रायता',
    category: 'meal',
    quantityPlates: 110,
    quantityKg: 38,
    sourceName: 'Golden Royal Banquet Hall',
    sourceNameHi: 'गोल्डन रॉयल बैंक्वेट हॉल',
    locationArea: 'Wazirpur Industrial / Ashok Vihar',
    locationAreaHi: 'अशोक विहार, दिल्ली',
    coords: { x: 310, y: 280 },
    readySinceMinutes: 90,
    safeForHours: 2.8,
    preparedAt: '01:00 PM',
    condition: 'fresh',
    freshnessScore: 88,
    classification: 'DONATE',
    classificationConfidence: 95,
    classificationReason: 'Large institutional catering excess; blast insulated before 2-hour standard mark.',
    classificationReasonHi: 'विवाह समारोह का अतिरिक्त शुद्ध शाकाहारी भोजन, स्वच्छ फूड-कंटेनरों में सीलबंद।',
    allergens: ['Milk / Lactose', 'Nuts (traces)'],
    allergensHi: ['दूध / लैक्टोज', 'मेवे'],
    isVeg: true,
    aiVerified: true,
    claimed: false,
    bestMatch: {
      ngoId: 'ngo-5',
      ngoName: 'Shastri Nagar Community Kitchen',
      ngoNameHi: 'शास्त्री नगर कम्युनिटी किचन',
      distanceKm: 1.4,
      etaMin: 5,
      lossScore: 0.0780,
      matchScore: 98,
      reasons: ['High capacity match', 'Instant hot-hold counters ready']
    }
  },
  {
    id: 'meal-005',
    dishName: 'Poha with Roasted Peanuts & Lemon',
    dishNameHi: 'पोहा भुनी मूंगफली व नींबू',
    category: 'snack',
    quantityPlates: 50,
    quantityKg: 12,
    sourceName: 'GTB Nagar Student Cafeteria',
    sourceNameHi: 'GTB नगर छात्र कैफेटेरिया',
    locationArea: 'Hudson Lane, GTB Nagar',
    locationAreaHi: 'हडसन लेन, GTB नगर',
    coords: { x: 460, y: 220 },
    readySinceMinutes: 110,
    safeForHours: 2.5,
    preparedAt: '10:45 AM',
    condition: 'fresh',
    freshnessScore: 87,
    classification: 'DONATE',
    classificationConfidence: 93,
    classificationReason: 'Light breakfast snack excess, dry preparation with high stability.',
    classificationReasonHi: 'सुबह का पौष्टिक नाश्ता, सूखी तैयारी होने के कारण स्थिर शेल्फ लाइफ।',
    allergens: ['Peanuts'],
    allergensHi: ['मूंगफली'],
    isVeg: true,
    aiVerified: true,
    claimed: false,
    bestMatch: {
      ngoId: 'ngo-4',
      ngoName: 'Night Shelter Majnu Ka Tila',
      ngoNameHi: 'रैन बसेरा मजनू का टीला',
      distanceKm: 1.9,
      etaMin: 7,
      lossScore: 0.0945,
      matchScore: 93,
      reasons: ['Close transit corridor', 'Ready for afternoon tea meal']
    }
  },
  {
    id: 'meal-006',
    dishName: 'Mixed Vegetable Prep Trimmings & Peels',
    dishNameHi: 'सब्जी छिलके एवं कटिंग अवशेष',
    category: 'staple',
    quantityPlates: 0,
    quantityKg: 45,
    sourceName: 'DTU Central Mess Kitchen',
    sourceNameHi: 'DTU सेंट्रल मेस किचन',
    locationArea: 'DTU Mess Loading Bay',
    locationAreaHi: 'DTU मेस लोडिंग बे',
    coords: { x: 210, y: 195 },
    readySinceMinutes: 140,
    safeForHours: 18,
    preparedAt: '09:30 AM',
    condition: 'stale',
    freshnessScore: 46,
    classification: 'RECYCLE',
    classificationConfidence: 97,
    classificationReason: 'Raw organic culinary trimmings (potato skins, pumpkin peels, cauliflower stalks). Zero microbial hazard; prime methane yield.',
    classificationReasonHi: 'सब्जी की तैयारी के ताजे अवशेष (आलू, कद्दू, फूलगोभी के छिलके)। बायोगैस ऊर्जा उत्पादन हेतु सर्वश्रेष्ठ।',
    allergens: ['None'],
    allergensHi: ['कोई नहीं'],
    isVeg: true,
    aiVerified: true,
    claimed: false,
    bestMatch: {
      ngoId: 'ngo-6',
      ngoName: 'DTU Campus Biogas & Vermicompost Plant',
      ngoNameHi: 'DTU बायो-ऊर्जा एवं खाद संयंत्र',
      distanceKm: 0.4,
      etaMin: 2,
      lossScore: 0.0420,
      matchScore: 99,
      reasons: ['Zero road transit required', 'Direct circular economy loop']
    }
  },
  {
    id: 'meal-007',
    dishName: 'Chana Masala & Steamed Rice',
    dishNameHi: 'चना मसाला एवं बासमती चावल',
    category: 'meal',
    quantityPlates: 55,
    quantityKg: 18,
    sourceName: 'Civil Lines Officers Mess',
    sourceNameHi: 'सिविल लाइन्स ऑफिसर्स मेस',
    locationArea: 'Sham Nath Marg, Civil Lines',
    locationAreaHi: 'शाम नाथ मार्ग, सिविल लाइन्स',
    coords: { x: 550, y: 340 },
    readySinceMinutes: 80,
    safeForHours: 3.5,
    preparedAt: '01:10 PM',
    condition: 'fresh',
    freshnessScore: 93,
    classification: 'DONATE',
    classificationConfidence: 96,
    classificationReason: 'High nutrition, sanitary stainless steel batch catering standard.',
    classificationReasonHi: 'उच्च पौष्टिकता, स्वच्छ स्टेनलेस स्टील कैटरिंग बर्तनों में सुरक्षित।',
    allergens: ['None'],
    allergensHi: ['कोई नहीं'],
    isVeg: true,
    aiVerified: true,
    claimed: false,
    bestMatch: {
      ngoId: 'ngo-2',
      ngoName: 'Roti Bank Civil Lines',
      ngoNameHi: 'रोटी बैंक सिविल लाइन्स',
      distanceKm: 0.6,
      etaMin: 3,
      lossScore: 0.0520,
      matchScore: 99,
      reasons: ['Immediate walking distance', 'Full cold/hot chain capacity']
    }
  },
  {
    id: 'meal-008',
    dishName: 'Moong Dal Halwa & Gulab Jamun',
    dishNameHi: 'मूंग दाल हलवा एवं गुलाब जामुन',
    category: 'sweets',
    quantityPlates: 45,
    quantityKg: 11,
    sourceName: 'Ashok Vihar Celebration Center',
    sourceNameHi: 'अशोक विहार सेलिब्रेशन सेंटर',
    locationArea: 'Deep Cinema Road, Ashok Vihar',
    locationAreaHi: 'अशोक विहार, दिल्ली',
    coords: { x: 325, y: 295 },
    readySinceMinutes: 120,
    safeForHours: 6.0,
    preparedAt: '12:00 PM',
    condition: 'fresh',
    freshnessScore: 95,
    classification: 'DONATE',
    classificationConfidence: 97,
    classificationReason: 'High sugar osmolality preserves shelf life; clean desi ghee preparation.',
    classificationReasonHi: 'देसी घी एवं मिठास के कारण उच्च स्थिरता; बच्चों व आश्रयों हेतु विशेष ऊर्जावर्धक मिठाई।',
    allergens: ['Milk / Lactose', 'Wheat / Gluten'],
    allergensHi: ['दूध / लैक्टोज', 'गेहूं'],
    isVeg: true,
    aiVerified: true,
    claimed: false,
    bestMatch: {
      ngoId: 'ngo-7',
      ngoName: 'Vivekanand Puri Seva Kendra',
      ngoNameHi: 'विवेकानंद पुरी सेवा केंद्र',
      distanceKm: 1.2,
      etaMin: 4,
      lossScore: 0.0610,
      matchScore: 97,
      reasons: ['Community youth center celebration match']
    }
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    kitchenName: 'Atal Canteen (DTU)',
    name: 'Basmati Rice (Grade A)',
    nameHi: 'बासमती चावल',
    quantity: 120,
    unit: 'kg',
    lastUpdated: '10:30 AM Today',
    sha256Hash: 'a7f34c98e102834bdf8821034cbb6219'
  },
  {
    id: 'inv-2',
    kitchenName: 'Atal Canteen (DTU)',
    name: 'Toor Dal Organic',
    nameHi: 'अरहर दाल जैविक',
    quantity: 45,
    unit: 'kg',
    lastUpdated: '10:30 AM Today',
    sha256Hash: 'b94e8201fa88432190cd531a7bc8102d'
  },
  {
    id: 'inv-3',
    kitchenName: 'Atal Canteen (DTU)',
    name: 'Sharbati Whole Wheat Atta',
    nameHi: 'शरबती गेहूं आटा',
    quantity: 90,
    unit: 'kg',
    lastUpdated: '09:15 AM Today',
    sha256Hash: 'c301492ba87129f109bc489a5281ea09'
  },
  {
    id: 'inv-4',
    kitchenName: 'DTU Central Mess (Hostels)',
    name: 'Fresh Farm Green Peas',
    nameHi: 'ताजा हरी मटर',
    quantity: 60,
    unit: 'kg',
    lastUpdated: '08:00 AM Today',
    sha256Hash: 'd8839210bc740192ea6201bba7219904'
  },
  {
    id: 'inv-5',
    kitchenName: 'DTU Central Mess (Hostels)',
    name: 'Full Cream Milk Cans',
    nameHi: 'फुल क्रीम दूध',
    quantity: 180,
    unit: 'liters',
    lastUpdated: '07:30 AM Today',
    sha256Hash: 'e102948bbca91204856cd8120349af71'
  }
];

export const GOSSIP_NODES: GossipNode[] = [
  { id: 'node-dtu-atal', name: 'Atal Canteen Node', type: 'canteen', coords: { x: 180, y: 140 }, lastSynced: 'Just now', isPulsing: true },
  { id: 'node-dtu-mess', name: 'Hostel Mess Node', type: 'canteen', coords: { x: 260, y: 190 }, lastSynced: '2m ago', isPulsing: false },
  { id: 'node-sewa-ngo', name: 'Sewa Kamla Nagar', type: 'ngo', coords: { x: 440, y: 310 }, lastSynced: '1m ago', isPulsing: true },
  { id: 'node-roti-bank', name: 'Civil Lines Node', type: 'ngo', coords: { x: 570, y: 360 }, lastSynced: '4m ago', isPulsing: false },
  { id: 'node-robin-hood', name: 'Robin Hood Army', type: 'ngo', coords: { x: 490, y: 270 }, lastSynced: 'Just now', isPulsing: true },
  { id: 'node-shastri', name: 'Shastri Community', type: 'community', coords: { x: 330, y: 410 }, lastSynced: '3m ago', isPulsing: false },
  { id: 'node-central-hub', name: 'SIH Central Ledger', type: 'hub', coords: { x: 380, y: 220 }, lastSynced: 'Synchronized', isPulsing: true }
];

export const CANTEEN_PREDICTIONS = [
  {
    canteen: 'Atal Canteen (DTU)',
    canteenHi: 'अटल कैंटीन (DTU)',
    predictedSurplusPlates: 35,
    predictedTime: 'After 08:30 PM tonight',
    predictedTimeHi: 'आज रात 8:30 के बाद',
    confidence: '92% Historical Accuracy',
    dish: 'Rajma / Chawal Batch',
    trend: [18, 25, 32, 29, 35, 38, 35]
  },
  {
    canteen: 'DTU Mess Block B',
    canteenHi: 'DTU मेस ब्लॉक B',
    predictedSurplusPlates: 55,
    predictedTime: 'After 09:15 PM tonight',
    predictedTimeHi: 'आज रात 9:15 के बाद',
    confidence: '88% Attendance Model',
    dish: 'Dal Tadka + Phulkas',
    trend: [40, 48, 52, 45, 60, 50, 55]
  },
  {
    canteen: 'GTB Student Cafeteria',
    canteenHi: 'GTB छात्र कैफेटेरिया',
    predictedSurplusPlates: 20,
    predictedTime: 'After 07:45 PM tonight',
    predictedTimeHi: 'आज शाम 7:45 के बाद',
    confidence: '94% Exam Season Trend',
    dish: 'Paneer Kulcha & Poha',
    trend: [12, 15, 22, 18, 25, 20, 20]
  }
];
